---
    name: Continuous Integration
    on:
      workflow_dispatch:
      workflow_call:
      schedule:
        - cron: '0 4 * * 1-5'

    jobs:
      build-container:
        uses: ./.github/workflows/build-docker-container.yml
        secrets: inherit
        permissions:
          contents: read
          packages: write

      compose-container:
        uses: ./.github/workflows/compose-container.yml
        secrets: inherit

      trivy-scan:
        uses: ./.github/workflows/trivy.yml
        secrets: inherit
        permissions:
          contents: read
          packages: write
          actions: read
          security-events: write

      create-pr:
        uses: ./.github/workflows/create-pr.yml
        secrets: inherit
        permissions:
          pull-requests: write
