---
name: Compose Container
on:
    workflow_dispatch:
    workflow_call:
jobs:
    boot-container:
      name: Spin the Container up
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Docker Compose Up
          working-directory: ./Docker
          run: docker compose up

    # linting:

    container-down:
      name: Shut down the Container
      needs: [boot-container]
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Docker Compose Down
          working-directory: ./Docker
          run: |
            docker compose down
