---
name: Create Pull Request From Main to Release
on:
  workflow_call:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.SECRET_TOKEN }}

jobs:
    check-commit:
      runs-on: ubuntu-latest
      name: Check For a Commit
      outputs:
        should_run: ${{ steps.should_run.outputs.should_run }}
      steps:
        - uses: actions/checkout@v3
        - name: Print Latest Commit
          run: echo ${{ github.sha }}

        - name: Check if There Has Been A Commit
          id: should_run
          continue-on-error: false
          run: |
            sha=$(git rev-list --after="24 hours" ${{ github.sha }})
                if test -z $sha
            then
                echo "should_run=false" >> $GITHUB_OUTPUT
            else
                echo "should_run=true" >> $GITHUB_OUTPUT
            fi

    pull-request:
      name: Create Pull Request
      needs: [check-commit]
      if: ${{ needs.check-commit.outputs.should_run != 'false' }}
      runs-on: ubuntu-latest
      outputs:
        pr_number: ${{ steps.pr-number.outputs.pull_request_number }}
      steps:
        - uses: actions/checkout@v3
        - name: Get Current Date
          id: date
          run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

        - name: Get Git Short Commit
          id: git-short
          run: echo "short_sha=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

        - name: Open Pull Request
          id: open-pr
          run: gh pr create --label "autogenerated" --title "${{ steps.date.outputs.date }} Release" --body "Last commit being merged as ${{ steps.git-short.outputs.short_sha }}" --base release --head main

        - name: Get Pull Request Number
          id: pr-number
          run: echo "pull_request_number=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT

    auto-approve:
      name: Auto Aprove The Created Pull Request
      needs: [pull-request]
      if: ${{ needs.pull-request.outputs.pr_number != null }}
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
      steps:
        - uses: hmarr/auto-approve-action@v3
          with:
            pull-request-number: ${{ needs.pull-request.outputs.pr_number }}
            github-token: ${{ secrets.GITHUB_TOKEN }}

    auto-merge:
      name: Auto Merge The Created Pull Request
      needs: [auto-approve, pull-request]
      if: ${{ needs.pull-request.outputs.pr_number != null }}
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
      steps:
        - id: automerge
          name: automerge
          uses: pascalgn/automerge-action@v0.15.6
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #merge_retries: 50
            #merge_retry_sleep: 30000
            merge_method: squash
