---
name: Create Release
on:
  push:
    branches:
      - release

jobs:
  trivy-scan:
    uses: ./.github/workflows/trivy.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write
    with:
      work-dir: ./Docker

  release:
    needs: [trivy-scan]
    permissions: write-all
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Current Date
        id: date
        run: |
          echo "date=$(date +%Y%m%d:%H%M)" >> $GITHUB_OUTPUT
          echo "tag=$(date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT

      - name: Changelog
        uses: Bullrich/generate-release-changelog@master
        id: changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        with:
          tag_name: v.1${{ steps.date.outputs.tag }}
          release_name: Release ${{ steps.date.outputs.date }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
