name: Linting
on:
  pull_request:
    branches:
      - release
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  workflow_dispatch:
jobs:
  yamllint:
    permissions:
      contents: read
      pull-requests: write
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Yamllint
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_strict: true
          yamllint_format: parsable
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
