---
name: Test Marketplace Action
on:
  workflow_dispatch:

jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

  build-and-publish:
    needs: [checkout]
    name: Testing Action
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build and Publish Container
        uses: Bombarding/build-and-publish@v1.202402160414
        with:
          docker-name: local-container
          image-name: web-container
          github-repo: bombarding/build-and-publish
          work-dir: './Docker'
