---
name: Testing Tags
on:
  push:
    tags:
      - v1.*

jobs:
  trivy-scan:
    if: startsWith(github.ref, 'refs/tags/v2.')
    uses: ./.github/workflows/trivy.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      actions: read
      security-events: write
    with:
      work-dir: ./Docker
