---
name: Test Marketplace Action
on:
  workflow_dispatch:

jobs:
  action:
    name: Testing Action
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Build and Publish Container
        uses: Bombarding/build-and-publish@v1.0
        with:
          docker-name: local-container
          image-name: web-container
          github-repo: bombarding/build-and-publish
          work-dir: ./Docker
