---
name: Test Marketplace Action
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.SECRET_TOKEN }}

jobs:
  action:
    name: Build and Publish Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build and Publish Container
        uses: Bombarding/build-and-publish@v1.0
        with:
          docker-name: local-container
          image-name: web-container
          github-repo: bombarding/build-and-publish
          work-dir: ./Docker
